### ISSUE TITLE
portal-embed-demo: it is failed to build by fsevents@1.2.8 on Node v12

### ISSUE THREAD

**Issue by ka2jun8** [WICG/portals#161]
It is failed to node-gyp build on Node v12.

The `gulp@4.0.1` depends on `fsevents@^1.2.7` through `glob-watcher@5.0.3`, `chokidar@2.1.5`.
`portal-embed-demo` depends on `fsevents@1.2.8` in `package-lock.json` (https://github.com/ka2jun8/portals/blob/master/demos/portal-embed-demo/package-lock.json#L1573-L1574).
This fsevents version 1.2.8 is reported that it is failed to build on node v12 (https://github.com/nodejs/node/issues/27389, https://github.com/fsevents/fsevents/issues/278).

I think that it needs to update fsevents@1.2.9.

But, glob-watcher issue say that it cannot update chokidar v3 (https://github.com/gulpjs/glob-watcher/issues/49). So it cannot update fsevents@1.2.9 through gulp structurally.

By the way, in my local Macbook pro, I changed gulp in package.json to `"gulp": "^4.0.2",` and I tried re-installing npm modules.  
The `chokidar@v2.1.8` is installed implicitly, and I succeeded to install `fsevents@1.2.9` and to build it.
But I do not know it is collect way, because I did not tried it in Windows.

I will show this issue following the failing logs of my npm install and npm ls.

```
➜  portal-embed-demo git:(master) node -v
v12.13.0
➜  portal-embed-demo git:(master) npm -v
6.12.0
➜  portal-embed-demo git:(master) npm i

> fsevents@1.2.8 install /Users/junya/Programs/wicg/portals/demos/portal-embed-demo/node_modules/fsevents
> node install

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.8/fse-v1.2.8-node-v72-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.8 and node@12.13.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
../fsevents.cc:43:32: error: no template named 'Handle' in namespace 'v8'
    static void Initialize(v8::Handle<v8::Object> exports);
                           ~~~~^
In file included from ../fsevents.cc:73:
../src/constants.cc:89:11: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagNone").ToLo...
          ^
/Users/junya/Library/Caches/node-gyp/12.13.0/include/node/v8.h:3402:3: note:
      'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/junya/Library/Caches/node-gyp/12.13.0/include/node/v8config.h:311:29: note:
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:73:
../src/constants.cc:90:11: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagMustScanSub...
          ^
/Users/junya/Library/Caches/node-gyp/12.13.0/include/node/v8.h:3402:3: note:
      'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/junya/Library/Caches/node-gyp/12.13.0/include/node/v8config.h:311:29: note:
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:73:
../src/constants.cc:91:11: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagUserDropped...
          ^
/Users/junya/Library/Caches/node-gyp/12.13.0/include/node/v8.h:3402:3: note:
      'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/junya/Library/Caches/node-gyp/12.13.0/include/node/v8config.h:311:29: note:
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:73:
../src/constants.cc:92:11: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagKernelDropp...
          ^
/Users/junya/Library/Caches/node-gyp/12.13.0/include/node/v8.h:3402:3: note:
      'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/junya/Library/Caches/node-gyp/12.13.0/include/node/v8config.h:311:29: note:
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:73:
../src/constants.cc:93:11: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagEventIdsWra...
          ^
/Users/junya/Library/Caches/node-gyp/12.13.0/include/node/v8.h:3402:3: note:
      'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/junya/Library/Caches/node-gyp/12.13.0/include/node/v8config.h:311:29: note:
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:73:
../src/constants.cc:94:11: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagHistoryDone...
          ^
/Users/junya/Library/Caches/node-gyp/12.13.0/include/node/v8.h:3402:3: note:
      'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/junya/Library/Caches/node-gyp/12.13.0/include/node/v8config.h:311:29: note:
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:73:
../src/constants.cc:95:11: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagRootChanged...
          ^
/Users/junya/Library/Caches/node-gyp/12.13.0/include/node/v8.h:3402:3: note:
      'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/junya/Library/Caches/node-gyp/12.13.0/include/node/v8config.h:311:29: note:
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:73:
../src/constants.cc:96:11: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagMount").ToL...
          ^
/Users/junya/Library/Caches/node-gyp/12.13.0/include/node/v8.h:3402:3: note:
      'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/junya/Library/Caches/node-gyp/12.13.0/include/node/v8config.h:311:29: note:
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:73:
../src/constants.cc:97:11: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagUnmount").T...
          ^
/Users/junya/Library/Caches/node-gyp/12.13.0/include/node/v8.h:3402:3: note:
      'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/junya/Library/Caches/node-gyp/12.13.0/include/node/v8config.h:311:29: note:
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:73:
../src/constants.cc:98:11: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemCreated...
          ^
/Users/junya/Library/Caches/node-gyp/12.13.0/include/node/v8.h:3402:3: note:
      'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/junya/Library/Caches/node-gyp/12.13.0/include/node/v8config.h:311:29: note:
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:73:
../src/constants.cc:99:11: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemRemoved...
          ^
/Users/junya/Library/Caches/node-gyp/12.13.0/include/node/v8.h:3402:3: note:
      'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/junya/Library/Caches/node-gyp/12.13.0/include/node/v8config.h:311:29: note:
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:73:
../src/constants.cc:100:11: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemInodeMe...
          ^
/Users/junya/Library/Caches/node-gyp/12.13.0/include/node/v8.h:3402:3: note:
      'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/junya/Library/Caches/node-gyp/12.13.0/include/node/v8config.h:311:29: note:
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:73:
../src/constants.cc:101:11: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemRenamed...
          ^
/Users/junya/Library/Caches/node-gyp/12.13.0/include/node/v8.h:3402:3: note:
      'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/junya/Library/Caches/node-gyp/12.13.0/include/node/v8config.h:311:29: note:
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:73:
../src/constants.cc:102:11: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemModifie...
          ^
/Users/junya/Library/Caches/node-gyp/12.13.0/include/node/v8.h:3402:3: note:
      'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/junya/Library/Caches/node-gyp/12.13.0/include/node/v8config.h:311:29: note:
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:73:
../src/constants.cc:103:11: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemFinderI...
          ^
/Users/junya/Library/Caches/node-gyp/12.13.0/include/node/v8.h:3402:3: note:
      'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/junya/Library/Caches/node-gyp/12.13.0/include/node/v8config.h:311:29: note:
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:73:
../src/constants.cc:104:11: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemChangeO...
          ^
/Users/junya/Library/Caches/node-gyp/12.13.0/include/node/v8.h:3402:3: note:
      'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/junya/Library/Caches/node-gyp/12.13.0/include/node/v8config.h:311:29: note:
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:73:
../src/constants.cc:105:11: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemXattrMo...
          ^
/Users/junya/Library/Caches/node-gyp/12.13.0/include/node/v8.h:3402:3: note:
      'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/junya/Library/Caches/node-gyp/12.13.0/include/node/v8config.h:311:29: note:
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:73:
../src/constants.cc:106:11: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemIsFile"...
          ^
/Users/junya/Library/Caches/node-gyp/12.13.0/include/node/v8.h:3402:3: note:
      'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/junya/Library/Caches/node-gyp/12.13.0/include/node/v8config.h:311:29: note:
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:73:
../src/constants.cc:107:11: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemIsDir")...
          ^
/Users/junya/Library/Caches/node-gyp/12.13.0/include/node/v8.h:3402:3: note:
      'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/junya/Library/Caches/node-gyp/12.13.0/include/node/v8config.h:311:29: note:
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:73:
../src/constants.cc:108:11: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemIsSymli...
          ^
/Users/junya/Library/Caches/node-gyp/12.13.0/include/node/v8.h:3402:3: note:
      'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/junya/Library/Caches/node-gyp/12.13.0/include/node/v8config.h:311:29: note:
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../fsevents.cc:76:16: error: variable has incomplete type 'void'
void FSEvents::Initialize(v8::Handle<v8::Object> exports) {
               ^
../fsevents.cc:76:31: error: no member named 'Handle' in namespace 'v8'
void FSEvents::Initialize(v8::Handle<v8::Object> exports) {
                          ~~~~^
../fsevents.cc:76:48: error: expected '(' for function-style cast or type
      construction
void FSEvents::Initialize(v8::Handle<v8::Object> exports) {
                                     ~~~~~~~~~~^
../fsevents.cc:76:50: error: use of undeclared identifier 'exports'
void FSEvents::Initialize(v8::Handle<v8::Object> exports) {
                                                 ^
../fsevents.cc:76:58: error: expected ';' after top level declarator
void FSEvents::Initialize(v8::Handle<v8::Object> exports) {
                                                         ^
                                                         ;
20 warnings and 6 errors generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/junya/.nodebrew/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/Users/junya/.nodebrew/node/v12.13.0/bin/node" "/Users/junya/.nodebrew/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/junya/Programs/wicg/portals/demos/portal-embed-demo/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/junya/Programs/wicg/portals/demos/portal-embed-demo/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /Users/junya/Programs/wicg/portals/demos/portal-embed-demo/node_modules/fsevents
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/junya/.nodebrew/node/v12.13.0/bin/node /Users/junya/.nodebrew/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/junya/Programs/wicg/portals/demos/portal-embed-demo/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/junya/Programs/wicg/portals/demos/portal-embed-demo/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/junya/Programs/wicg/portals/demos/portal-embed-demo/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Darwin 18.7.0
node-pre-gyp ERR! command "/Users/junya/.nodebrew/node/v12.13.0/bin/node" "/Users/junya/Programs/wicg/portals/demos/portal-embed-demo/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/junya/Programs/wicg/portals/demos/portal-embed-demo/node_modules/fsevents
node-pre-gyp ERR! node -v v12.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
Failed to execute '/Users/junya/.nodebrew/node/v12.13.0/bin/node /Users/junya/.nodebrew/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/junya/Programs/wicg/portals/demos/portal-embed-demo/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/junya/Programs/wicg/portals/demos/portal-embed-demo/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 471 packages from 304 contributors and audited 6976 packages in 16.533s
found 0 vulnerabilities

➜  portal-embed-demo git:(master) npm ls fsevents
portal-embed-demo@1.0.0 /Users/junya/Programs/wicg/portals/demos/portal-embed-demo
└─┬ gulp@4.0.1
  └─┬ glob-watcher@5.0.3
    └─┬ chokidar@2.1.5
      └── UNMET OPTIONAL DEPENDENCY fsevents@1.2.8
```

**Comment by jeremyroman** [comment]
@uskay do you know how to resolve this?
